matrix:
    include:
        - os: linux
          sudo: required
          dist: trusty
          install:
            - ./setup
        - os: osx
          install:
            - sudo easy_install pip
            - sudo pip install --upgrade pip
            - ./setup
script:
  - cd ./firmware/FreeRTOS/
  - source env.sh
  - make build
  - ls ./bin/firmware.symbols.elf
  - ls ./bin/firmware.symbols.hex
  - ls ./bin/firmware.symbols.lst
  - ls ./bin/firmware.map
  - ls ./bin/firmware.sym
  - ls ./bin/symbol-table.c
  - make nosym-build
  - ls ./bin/firmware.elf
  - ls ./bin/firmware.hex
  - ls ./bin/firmware.lst
  - ls ./bin/firmware.map
  - ls ./bin/firmware.sym
  - cd test/simple-test/
  - make