language: cpp
matrix:
    include:
        - os: linux
          sudo: required
          dist: trusty
          install:
            - ./setup
        - os: osx
          install:
            - sudo easy_install pip
            - sudo pip install --upgrade pip
            - ./setup
script:
  - cd ./firmware/Starter/
  - source env.sh
  - make build
  - ls ./build/bin/firmware.elf
  - ls ./build/bin/firmware.hex
  - ls ./build/bin/firmware.lst
  - ls ./build/bin/firmware.map
  - ls ./build/bin/firmware.sym
  - cd ../examples/FreeRTOS/
  - source env.sh
  - make build
  - ls ./build/bin/firmware.elf
  - ls ./build/bin/firmware.hex
  - ls ./build/bin/firmware.lst
  - ls ./build/bin/firmware.map
  - ls ./build/bin/firmware.sym